name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 4 * * *" # 每天 UTC 时间 04:00 (北京时间中午 12:00) 运行
  workflow_dispatch: # 允许手动点击按钮运行

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: 检出你的代码
      - name: Checkout target repo
        uses: actions/checkout@v3

      # Step 2: 执行同步
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: Stardm0/MoonTV
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 自动生成，无需设置
          test_mode: false

      # Step 3: 失败检查
      - name: Sync check
        if: failure()
        run: |
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
          exit 1
